#config_base
# copy from https://esphome.io/guides/configuration-types.html
# base config for all ESPHome
# version 1.1 KL 2021-09-25
# utility meter

substitutions:
   node_name: utilitymeter
   upper_node_name: Utility Meter
   platform: esp32
   # select from http://docs.platformio.org/en/latest/platforms/espressif32.html#boards
   eboard: esp32dev
   static_ip: 192.168.1.11
   gateway: 192.168.1.1
   log_level: VERY_VERBOSE


packages:
  wifi: !include common/packages/wifi.yaml
  device_base: !include common/packages/device_basenologser_aud.yaml
  time: !include common/packages/time_sntp.yaml

external_components:
#  - source: github://pr#8009
#    components: [ dlms_meter ]
#  - source: github://gstos/esphome-line-server
#    components: [line_server]
# Include the custom M-Bus component
  - source: 
      type: local
      path: components
#line_server:
#  uart_id: uart_bus
#  uart_terminator: 7E\r

api: 

#i2c:
#  sda: GPIO21
#  scl: GPIO22

uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 2400  # Norwegian HAN standard baud rate
  rx_buffer_size: 2048  # Increased buffer size for complete M-Bus frames
  # Uncomment for debugging UART communication:
  # debug:
  #   direction: RX
  #   dummy_receiver: false
  #   after:
  #     delimiter: [0x7E]
  #     timeout: 1000ms
  #     bytes: 2048
  #   sequence:
  #     - lambda: UARTDebug::log_hex(direction, bytes, ' ');  

# Norwegian HAN M-Bus component configuration
mbus_meter:
  id: mbus_reader
  uart_id: uart_bus
  # Component automatically handles Norwegian HAN OBIS codes
  # Supports AIDON_V0001 and compatible meters
  
# Sensors and more
sensor:

  # Norwegian HAN M-Bus Meter Sensors (AIDON_V0001)
  - platform: mbus_meter
    id: mbus_reader
    
    # Power measurements
    power:
      name: "AMS Power consumption"
      unit_of_measurement: W
      device_class: power
      state_class: measurement
      accuracy_decimals: 0
      icon: mdi:flash-outline
      
    # Current measurements (3-phase)
    current_l1:
      name: "AMS Amp L1"
      unit_of_measurement: A
      device_class: current
      state_class: measurement
      accuracy_decimals: 1
      
    current_l2:
      name: "AMS Amp L2"
      unit_of_measurement: A
      device_class: current
      state_class: measurement
      accuracy_decimals: 1
      
    current_l3:
      name: "AMS Amp L3"
      unit_of_measurement: A
      device_class: current
      state_class: measurement
      accuracy_decimals: 1
      
    # Voltage measurements (3-phase)
    voltage_l1:
      name: "AMS Volt L1"
      unit_of_measurement: V
      device_class: voltage
      state_class: measurement
      accuracy_decimals: 1
      
    voltage_l2:
      name: "AMS Volt L2"
      unit_of_measurement: V
      device_class: voltage
      state_class: measurement
      accuracy_decimals: 1
      
    voltage_l3:
      name: "AMS Volt L3"
      unit_of_measurement: V
      device_class: voltage
      state_class: measurement
      accuracy_decimals: 1
      
    # Energy measurements
    energy:
      name: "AMS Energy Usage"
      unit_of_measurement: Wh
      device_class: energy
      state_class: total_increasing
      accuracy_decimals: 0
      
    # Reactive power measurements
    reactive_power:
      name: "AMS Reactive Power"
      unit_of_measurement: var
      device_class: reactive_power
      state_class: measurement
      accuracy_decimals: 0
      
    reactive_energy:
      name: "AMS Reactive Energy Import"
      unit_of_measurement: varh
      device_class: energy
      state_class: total_increasing
      accuracy_decimals: 0
      
    reactive_export_energy:
      name: "AMS Reactive Energy Export"
      unit_of_measurement: varh
      device_class: energy
      state_class: total_increasing
      accuracy_decimals: 0
      
    # Export sensors - now supported in A1 frames
    # These sensors will show export power/energy if your meter supports it
    # Values will be 0 if no export is occurring
    # export_power:
    #   name: "AMS Export Power"
    #   unit_of_measurement: W
    #   device_class: power
    #   state_class: measurement
    #   accuracy_decimals: 0
    #   icon: mdi:flash-outline
    #   
    # export_energy:
    #   name: "AMS Export Energy"
    #   unit_of_measurement: Wh
    #   device_class: energy
    #   state_class: total_increasing
    #   accuracy_decimals: 0
    #
    # reactive_export_energy:
    #   name: "AMS Reactive Export Energy"
    #   unit_of_measurement: varh
    #   device_class: energy
    #   state_class: total_increasing
    #   accuracy_decimals: 0

  - !include common/sensor/uptime.yaml
  - !include common/sensor/wifi-signal.yaml
  - platform: pulse_meter
    pin: GPIO26
    internal_filter: 100ms
    timeout: 10min
    state_class: measurement
    device_class: power
    icon: mdi:flash-outline
    name: '${upper_node_name} Power consumption'
    unit_of_measurement: 'W'
    filters:
       - filter_out: 60000
#      - lambda: return x * ((60.0 / 1000) * 1000.0);
       - multiply: 60
    total:
      name: '${upper_node_name} Total energy'
      unit_of_measurement: 'kWh'
      icon: mdi:circle-slice-3
      state_class: total_increasing
      device_class: energy
      accuracy_decimals: 3
      filters:
        - lambda: return x * (1.0 / 1000);


binary_sensor:
#  - platform: stream_server
#    stream_server: streeams
    
  - !include common/binary_sensor/status.yaml

text_sensor:
  - !include common/text_sensor/esphome_version.yaml
  
  # Norwegian HAN M-Bus Meter Text Sensors
  - platform: mbus_meter
    id: mbus_reader
    
    # OBIS List version identifier (1.1.0.2.129.255)
    obis_version:
      name: "AMS OBIS Version"
      icon: mdi:information-outline
      
    # Meter ID (0.0.96.1.0.255)
    meter_id:
      name: "AMS Meter ID"
      icon: mdi:identifier
      
    # Meter type (0.0.96.1.7.255)
    meter_type:
      name: "AMS Meter Type"
      icon: mdi:gauge
      
#  - platform: dlms_meter
#    timestamp:
#      name: "timestamp"
#    # EVN
#    meternumber:
#      name: "meterNumber"
button:
  - !include common/switch/reboot.yaml
